name: Swift

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  test:

    runs-on: macos-latest
    
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=15.2,name=iPhone 13']
        xcode: ['/Applications/Xcode_13.2.1.app/Contents/Developer']
        
    steps:
    - uses: actions/checkout@v2      
    - name: Build and test
      run: bundle exec fastlane scan --destination "${destination}"
      env:
        destination: ${{ matrix.destination }}
        DEVELOPER_DIR: ${{ matrix.xcode }}
        
